### ISSUE TITLE
Plotting a chart when data is empty causes the app to crash

### ISSUE THREAD

**Issue by rishsriv** [defog-ai/defog-components#7]
On the experimental `chart-table-tabs` branch, plotting a chart when the underlying data is empty or `null` causes an error.

To replicate: ask a question like "plot a chart of our monthly revenue in the last year". This will cause the app to crash, since there is no real underlying data (the dataset is only for 2008).

I think this is because there isn't exception handling for scenarios where we might have an empty array – but not 100% sure. I tried to fix it myself, but ended up causing an unintended error because I don't understand the codebase super well yet and so rolled back the changed 😅

**Comment by man-shar** [comment]
fixed in ba8ddaf
