### ISSUE TITLE
Can we move computation of column types to the front-end, for backward compatability?

### ISSUE THREAD

**Issue by rishsriv** [defog-ai/defog-components#8]
Right now, the app works when running locally with the `manas-charts` branch of defog-backend-local. However we would have to ask all customers to install a new microservice in order to bring this to production.

To avoid that, can we move some of the computation to the frontend? We can use the endpoint `https://test-defog-ikcpfh5tva-uc.a.run.app/` (contains the default redshift dataset) to test if this will work in production!

**Comment by man-shar** [comment]
done in [c0bc384](https://github.com/defog-ai/defog-components/commit/c0bc384eabe492300d8ab538d88b16abd5ad8656)

**Comment by rishsriv** [comment]
Amazing, thank you!
